P rupdates
JEub/dev-this-address-book pull request #7
Opened 2023-05-12 23:00 UTC by e-t-trudell

Resolved pull request conflicts from PR#6
https://github.com/JEub/dev-this-address-book/pull/6

Updated read me in both root and frontend directories
Added Nav.css to condense styling for easier imports instead of using react styled components
removed extra white space in App.js

2023-05-16 01:02 UTC, JEub requested changes

2023-05-16 01:02 UTC, JEub commented on README.md
> +To run frontend from the terminal: cd frontend cd addressbook npm run dev
Start this section as a new section in the readme. Call it 

## Getting Started

To run the front end application in a unix terminal

```bash
# change into the address book directory
cd ./frontend/addressbook/

# run the development environment for hot reloads
npm run dev
```

2023-05-16 01:02 UTC, JEub commented on frontend/address-book/src/App.jsx
> +    return (
Make sure to pull and merge from main.

2023-05-16 01:02 UTC, JEub commented on frontend/address-book/src/components/Nav.jsx
> +                    <a href="/">Add Customer</a>
According to @parradaniela "a button should do something, and an anchor should take you somewhere. You should avoid using both in the same area."

2023-05-16 01:02 UTC, JEub commented on frontend/address-book/src/components/SearchBar.jsx
> +    // const button = {
Lets get rid of these cSs comments

2023-05-16 01:02 UTC, JEub commented on frontend/address-book/src/utils/API.jsx
Remove!

2023-05-17 00:18 UTC, e-t-trudell commented on README.md
> +To run frontend from the terminal: cd frontend cd addressbook npm run dev
Corrected and pushed

2023-05-17 00:19 UTC, e-t-trudell commented on frontend/address-book/src/App.jsx
> +    return (
Corrected and pushed

2023-05-17 00:19 UTC, e-t-trudell commented on frontend/address-book/src/components/Nav.jsx
> +                    <a href="/">Add Customer</a>
Corrected and pushed

2023-05-17 00:19 UTC, e-t-trudell commented on frontend/address-book/src/components/SearchBar.jsx
> +    // const button = {
Corrected and pushed

2023-05-17 00:19 UTC, e-t-trudell commented on frontend/address-book/src/utils/API.jsx
Corrected and pushed

2023-05-17 00:20 UTC, e-t-trudell commented
Updated changes requested from yesterdays code review. Changes include updating treadles, removing npm package for axis that was not needed, removing css comments, pulling main branch to have updated frontend changes.

2023-05-17 20:04 UTC, JEub approved these changes

2023-05-17 20:05 UTC, JEub approved these changes

2023-05-17 20:05 UTC, merged